package com.highschoolhowto.audit;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    REGISTRATION_SUBMITTED,
    EMAIL_VERIFICATION_TRIGGERED,
    EMAIL_VERIFICATION_COMPLETED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED
}
