spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/highschoolhowto
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  links:
    verification: http://localhost:8080/api/auth/verify-email
    verification-redirect: http://localhost:4300/auth/login
    reset: http://localhost:4200/auth/reset-password

notifications:
  test:
    enabled: true
  graph:
    enabled: false
