--liquibase formatted sql

-- Rewrite help articles to match the actual locker UI.
-- The previously-described "Edit Mode" overlay, daily quote, stickers, and home-screen-with-app-icons
-- live in app-launcher.component which is no longer wired into the main locker flow.
-- The current locker uses app-pane-layout (desktop) and app-swipe-container (mobile).

-- ─── help-welcome ────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-welcome
UPDATE content_cards
SET
    body_html  = '<p>Your locker is your personal workspace on High School How To. Open it once and you''re set — no setup needed.</p><h3>What''s in your locker</h3><p>You''ve got four apps:</p><ul><li>📋 <strong>To-do</strong> — make lists, check things off, set due dates</li><li>📝 <strong>Notes</strong> — quick notes, study summaries, ideas</li><li>⏱ <strong>Timer</strong> — basic countdown or Pomodoro mode</li><li>📌 <strong>Pins</strong> — pinned web links to sites you use a lot</li></ul><h3>How it works</h3><p><strong>On a computer?</strong> Your active apps live side-by-side in panes. A small toolbar at the top lets you toggle apps on and off, change your locker color, and pick a font.</p><p><strong>On your phone?</strong> Swipe left and right to move between apps. All four apps are always there — the dots at the bottom show which one you''re on.</p><p>Take a look around and start using it.</p>',
    updated_at = now()
WHERE slug = 'help-welcome';
--rollback UPDATE content_cards SET body_html = '<p>Your locker is your personal space on High School How To. Think of it like your phone''s home screen — you''ve got apps, shortcuts, and a daily quote to keep you going.</p><p>Here''s what you''ll find:</p><ul><li><strong>Apps</strong> — To-do lists, notes, and timers to help you stay on top of things</li><li><strong>Shortcuts</strong> — quick links to sites you use all the time</li><li><strong>A daily quote</strong> — because sometimes you just need a little motivation</li><li><strong>Stickers</strong> — decorate your locker and make it yours</li></ul><p>Everything is set up and ready to go when you first sign in. No setup required. Just open your locker and start using it.</p><p><strong>On your phone?</strong> Your locker works just like swiping between app pages. Swipe left and right to switch between your active apps.</p><p><strong>On a computer?</strong> You''ll see your home screen with app icons. Your active apps open side by side so you can multitask.</p>', updated_at = now() WHERE slug = 'help-welcome';

-- ─── help-apps ───────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-apps
UPDATE content_cards
SET
    description = 'Overview of the four locker apps: To-do, Notes, Timer, and Pins.',
    body_html   = '<p>You have four apps in your locker:</p><table><thead><tr><th>App</th><th>What it does</th></tr></thead><tbody><tr><td>📋 <strong>To-do</strong></td><td>Make lists, check things off, set due dates</td></tr><tr><td>📝 <strong>Notes</strong></td><td>Jot down anything — study notes, reminders, ideas</td></tr><tr><td>⏱ <strong>Timer</strong></td><td>Basic countdown or Pomodoro mode for focused study</td></tr><tr><td>📌 <strong>Pins</strong></td><td>Pinned web links to your most-used sites</td></tr></tbody></table><h3>Opening an app</h3><p><strong>On a computer:</strong> active apps are always visible side-by-side as panes. Use the small icon buttons in the toolbar at the top to toggle apps on and off. You can have up to <strong>3 apps active</strong> at once.</p><p><strong>On your phone:</strong> swipe left and right to move between apps. All four apps are always available — no toggling needed.</p><h3>Inside an app</h3><p>Most apps hold multiple items — for example, the To-do app can hold many lists. When you open an app, you''ll see your items listed. Tap one to open it. Hit the back arrow to return to the list.</p><p>Your place is saved — switch apps and come back, you''re right where you left off.</p><h3>Rearranging your apps (desktop)</h3><p>Drag a pane''s header to swap it with another pane. Drag the divider between two panes to resize them. Each pane has buttons to maximize, restore, or close it.</p>',
    updated_at  = now()
WHERE slug = 'help-apps';
--rollback UPDATE content_cards SET description = 'Overview of the three locker apps: To-do, Notes, and Timer.', body_html = '<p>You have three apps in your locker:</p><table><thead><tr><th>App</th><th>What it does</th></tr></thead><tbody><tr><td>📋 <strong>To-do</strong></td><td>Make lists, check things off, stay organized</td></tr><tr><td>📝 <strong>Notes</strong></td><td>Jot down anything — study notes, reminders, ideas</td></tr><tr><td>⏱ <strong>Timer</strong></td><td>Set a basic countdown or use Pomodoro mode for focused study sessions</td></tr></tbody></table><h3>Opening an app</h3><p>Tap an app icon on your home screen. That''s it.</p><p>If you have more than one app active, they''ll show up side by side on a computer, or as swipeable pages on your phone.</p><h3>Active vs. inactive</h3><p>You can have up to <strong>3 apps active</strong> at the same time. Active apps are the ones that show up when you''re working. Inactive apps are still there — they''re just tucked away until you need them.</p><p>To change which apps are active, check out <a href="/content/help-edit-mode">Edit Mode</a>.</p><h3>Inside an app</h3><p>Most apps hold multiple items. For example, the To-do app can hold up to 20 different lists.</p><p>When you open an app, you''ll see all your items listed. Tap one to open it. Hit the back arrow to go back to the list.</p><p>Your place is saved — if you switch to another app and come back, you''ll be right where you left off.</p>', updated_at = now() WHERE slug = 'help-apps';

-- ─── help-todo ───────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-todo
UPDATE content_cards
SET
    body_html  = '<p>The To-do app is where you keep track of everything you need to get done.</p><h3>Creating a list</h3><ol><li>Open the 📋 To-do app</li><li>Tap <strong>+ New List</strong></li><li>Tap the title to rename it</li><li>Start adding tasks</li></ol><h3>Adding tasks</h3><p>Type in the <strong>Add a to-do…</strong> input at the bottom of your list and tap <strong>Add</strong> (or press Enter).</p><h3>Checking things off</h3><p>Tap the checkbox next to a task. It feels good, trust us.</p><h3>Due dates</h3><p>Tap the 📅 icon next to a task to set a due date. Once set, the date appears as a small badge on the task — overdue dates are highlighted. Tap the badge to change or clear the date.</p><h3>Other things you can do</h3><ul><li><strong>Rename a list or task</strong> — tap the title or task text to edit it inline</li><li><strong>Delete a task</strong> — tap the <strong>✕</strong> button next to it (you''ll be asked to confirm)</li><li><strong>Delete a list</strong> — tap the <strong>🗑</strong> icon (you''ll be asked to confirm)</li><li><strong>Change the list color</strong> — tap the colored circle next to the list to pick a new color</li></ul><h3>Importing a How To list</h3><p>Some How To articles come with a ready-made to-do list. When you see one, tap <strong>"Add to My Locker"</strong> and a personal copy will appear in your To-do app — edit it however you want.</p>',
    updated_at = now()
WHERE slug = 'help-todo';
--rollback UPDATE content_cards SET body_html = '<p>The To-do app is where you keep track of everything you need to get done.</p><h3>Creating a list</h3><ol><li>Open the 📋 To-do app</li><li>Tap <strong>+ New List</strong></li><li>Give it a name (or keep the default — you can rename it later)</li><li>Start adding tasks</li></ol><h3>Adding tasks</h3><p>Tap the <strong>+</strong> button at the bottom of your list. Type what you need to do, hit enter. Done.</p><h3>Checking things off</h3><p>Tap the checkbox next to a task. It feels good, trust us.</p><h3>Other things you can do</h3><ul><li><strong>Rename a list</strong> — tap the list title to edit it</li><li><strong>Reorder tasks</strong> — drag tasks up or down to prioritize</li><li><strong>Delete a task</strong> — swipe left on a task, or use the delete button</li><li><strong>Delete a list</strong> — look for the delete option in the list view (don''t worry, we''ll ask you to confirm first)</li><li><strong>Change the list color</strong> — pick a color to tell your lists apart at a glance</li></ul><h3>Importing a How To list</h3><p>Some How To articles come with a ready-made to-do list. When you see one, tap <strong>"Add to My Locker"</strong> and it''ll show up in your To-do app as a personal copy you can edit however you want.</p><h3>Limits</h3><p>You can have up to <strong>20 lists</strong>. If you hit the limit, try finishing or deleting one you don''t need anymore.</p>', updated_at = now() WHERE slug = 'help-todo';

-- ─── help-notes ──────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-notes
UPDATE content_cards
SET
    body_html  = '<p>Need to write something down fast? That''s what Notes is for.</p><h3>Creating a note</h3><ol><li>Open the 📝 Notes app</li><li>Tap <strong>+ New Note</strong></li><li>Tap the title to rename it</li><li>Start typing</li></ol><p>Notes save automatically when you tap away or go back to the list — no save button to remember.</p><h3>What you can do with notes</h3><ul><li><strong>Pick a color</strong> — tap the color picker to color-code your notes so they''re easy to spot</li><li><strong>Rename</strong> — tap the title to change it</li><li><strong>Delete</strong> — done with a note? Tap the delete button (you''ll be asked to confirm)</li></ul><h3>Tips</h3><ul><li>Use notes for quick reminders, study summaries, or brain dumps before a test</li><li>Keep it short — if your note is turning into an essay, maybe it''s time to open a doc instead</li></ul>',
    updated_at = now()
WHERE slug = 'help-notes';
--rollback UPDATE content_cards SET body_html = '<p>Need to write something down fast? That''s what Notes is for.</p><h3>Creating a note</h3><ol><li>Open the 📝 Notes app</li><li>Tap <strong>+ New Note</strong></li><li>Start typing</li></ol><h3>What you can do with notes</h3><ul><li><strong>Pick a color</strong> — color-code your notes so they''re easy to spot</li><li><strong>Rename</strong> — tap the title to change it</li><li><strong>Delete</strong> — done with a note? Delete it from the list view</li></ul><h3>Tips</h3><ul><li>Use notes for quick reminders, study summaries, or brain dumps before a test</li><li>Keep it short — if your note is turning into an essay, maybe it''s time to open a doc instead</li></ul><h3>Limits</h3><p>You can have up to <strong>20 notes</strong>.</p>', updated_at = now() WHERE slug = 'help-notes';

-- ─── help-timer ──────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-timer
UPDATE content_cards
SET
    body_html  = '<p>One timer, two modes. Open the ⏱ Timer app and pick the mode that fits what you''re doing using the tabs at the top.</p><h3>Basic Mode</h3><p>A simple countdown. Tap the time to set hours, minutes, and seconds, then hit <strong>Start</strong>. You''ll hear a chime when it''s done. Use <strong>Pause</strong> to stop the clock and <strong>Reset</strong> to start over.</p><p>Great for:</p><ul><li>Timed assignments</li><li>Quick breaks</li><li>"I''ll study for 30 more minutes" situations</li></ul><h3>Pomodoro Mode</h3><p>The Pomodoro technique breaks your work into focused chunks:</p><ol><li><strong>Focus session</strong> (25 minutes by default)</li><li><strong>Short break</strong> (5 minutes by default)</li><li><strong>Repeat</strong></li><li>After a few focus sessions, take a longer break (15 minutes by default)</li></ol><p>The timer cycles through these phases automatically — just tap <strong>Start</strong> and you''ll hear a chime at the end of each phase. Use <strong>Skip</strong> to jump to the next phase or <strong>Reset</strong> to start over.</p><p>The dots show how many focus sessions you''ve completed in the current cycle.</p><h3>Customizing Pomodoro</h3><p>Tap the <strong>⚙ gear icon</strong> in Pomodoro mode to adjust:</p><ul><li>Focus duration</li><li>Short break duration</li><li>Long break duration</li><li>How many focus sessions before the long break</li></ul><h3>Switching modes</h3><p>Tap the <strong>Basic</strong> or <strong>Pomodoro</strong> tab at the top. You can switch anytime the timer isn''t running.</p><h3>Why Pomodoro works</h3><p>Your brain stays fresher when you take regular breaks. It''s not about studying longer — it''s about studying smarter.</p>',
    updated_at = now()
WHERE slug = 'help-timer';
--rollback UPDATE content_cards SET body_html = '<p>One timer, two modes. Open the ⏱ Timer app and pick the mode that fits what you''re doing.</p><h3>Basic Mode</h3><p>A simple countdown. Set the time, hit start, and you''ll get a notification when it''s done. Great for:</p><ul><li>Timed assignments</li><li>Quick breaks</li><li>"I''ll study for 30 more minutes" situations</li></ul><h3>Pomodoro Mode</h3><p>The Pomodoro technique breaks your work into focused chunks:</p><ol><li><strong>Work for 25 minutes</strong> (one "pomodoro")</li><li><strong>Take a 5-minute break</strong></li><li><strong>Repeat</strong></li><li>After 4 pomodoros, take a longer 15-30 minute break</li></ol><p>The timer handles all of this automatically. Just hit start and follow along.</p><p><strong>Why it works:</strong> Your brain stays fresher when you take regular breaks. It''s not about studying longer — it''s about studying smarter.</p><h3>Switching modes</h3><p>Tap the mode toggle at the top of the timer to switch between Basic and Pomodoro. You can switch anytime you''re not mid-countdown.</p>', updated_at = now() WHERE slug = 'help-timer';

-- ─── help-edit-mode → "Customizing Your Locker" ──────────────────────────────
--changeset system:v5-help-accuracy-0065-edit-mode
UPDATE content_cards
SET
    title       = 'Customizing Your Locker',
    description = 'How to customize your locker: toggle apps, rearrange panes, change color, and pick a font.',
    body_html   = '<p>You can customize your locker''s look and contents — choose which apps appear, change the background color, pick a font, and rearrange your layout.</p><h3>The toolbar (desktop)</h3><p>The small toolbar at the top of your locker has everything you need:</p><ul><li><strong>App icons</strong> — tap to toggle each app on or off. Active apps appear as panes below. You can have up to <strong>3 apps active</strong> at once.</li><li><strong>Locker color button</strong> — tap the colored circle to open the color picker and change your locker''s background. See <a href="/content/help-palettes">Locker Color</a> for more.</li><li><strong>Font dropdown</strong> — pick a font for your apps, including dyslexia-friendly options like Lexend, Nunito, OpenDyslexic, and Comic Sans.</li></ul><h3>Rearranging panes (desktop)</h3><ul><li><strong>Reorder</strong> — drag a pane''s header onto another pane to swap their positions</li><li><strong>Resize</strong> — drag the divider between two panes to make one wider or narrower</li><li><strong>Maximize</strong> — use the maximize button in the pane header to make a pane fill the locker; minimize to bring the others back</li><li><strong>Close</strong> — use the close button in the pane header to deactivate that app</li></ul><h3>On mobile</h3><p>On your phone, all four apps are always available — just swipe between them. There''s no toggling or rearranging on mobile.</p><h3>Saving</h3><p>Your changes save automatically — there''s no save button to remember.</p>',
    updated_at  = now()
WHERE slug = 'help-edit-mode';
--rollback UPDATE content_cards SET title = 'Edit Mode', description = 'How to customize your locker: toggle apps, rearrange layout, pick a palette, and manage stickers.', body_html = '<p>Edit Mode is where you customize your locker. One place for everything.</p><h3>How to enter Edit Mode</h3><p>Tap the <strong>Customize</strong> button (pencil icon) on your home screen.</p><p>You''ll know you''re in Edit Mode because your app icons will start wiggling (yeah, like on an iPhone).</p><h3>What you can do in Edit Mode</h3><p><strong>Choose your active apps</strong></p><ul><li>Tap an app icon to toggle it on or off</li><li>A checkmark means it''s active</li><li>You can have up to 3 active at a time</li><li>Try to activate a 4th? It''ll give you a nudge to turn one off first</li></ul><p><strong>Rearrange your layout</strong></p><ul><li>Drag app panes to swap their positions</li><li>The layout auto-adjusts based on how many apps are active</li></ul><p><strong>Pick a color palette</strong></p><ul><li>Choose a theme that changes the look of all your apps at once</li><li>Options like Ocean, Sunset, Forest, and more</li><li>Each app gets its own color from the palette — coordinated but distinct</li></ul><p><strong>Manage stickers</strong></p><ul><li>Add new stickers to decorate your home screen</li><li>Drag them around to reposition</li><li>Tap to delete ones you don''t want</li></ul><p><strong>Manage Pins</strong></p><ul><li>Add, edit, reorder, or delete your quick links</li></ul><h3>Saving</h3><p>When you''re done, tap <strong>Done</strong>. Your changes save automatically.</p>', updated_at = now() WHERE slug = 'help-edit-mode';

-- ─── help-mobile ─────────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-mobile
UPDATE content_cards
SET
    description = 'How the locker works on your phone: swipe navigation and what''s different from desktop.',
    body_html   = '<p>Your locker is designed to work great on your phone.</p><h3>How it works on mobile</h3><ul><li><strong>All four apps, always</strong> — To-do, Notes, Timer, and Pins are all there as swipeable pages</li><li><strong>Swipe to switch</strong> — swipe left and right to move between apps</li><li><strong>Page dots</strong> — the dots at the bottom show which app you''re on. Tap a dot to jump to that page.</li></ul><h3>Inside each app</h3><p>Creating lists, writing notes, setting timers, adding pins — it all works the same as on a computer. The screen is just smaller, so you see one app at a time instead of side-by-side.</p><h3>What''s different from desktop</h3><p>The desktop view shows apps as panes you can rearrange, resize, and toggle on or off, with a toolbar at the top for changing the locker color and font. On mobile, every app is always available — there''s no concept of "active" apps to manage.</p>',
    updated_at  = now()
WHERE slug = 'help-mobile';
--rollback UPDATE content_cards SET description = 'How the locker works on your phone: swipe navigation, app drawer, and what''s different from desktop.', body_html = '<p>Your locker is designed to work great on your phone.</p><h3>How it''s different from desktop</h3><ul><li><strong>No home screen</strong> — you go straight to your apps</li><li><strong>Swipe to switch</strong> — swipe left and right to move between your active apps</li><li><strong>Page dots</strong> — the dots at the bottom show which app you''re on and how many you have</li><li><strong>Shortcuts and quote</strong> — your shortcuts and daily quote show at the top of your first app page</li><li><strong>Stickers</strong> — not visible on mobile (they''re a desktop/tablet thing)</li></ul><h3>Adding or removing apps on mobile</h3><p>Swipe past your last active app to find the <strong>app drawer</strong>. From there, you can tap apps to activate them.</p><p>To deactivate an app, use the settings icon in the app header or the app drawer.</p><h3>Everything else works the same</h3><p>Creating lists, writing notes, setting timers — it all works exactly like it does on a computer. The screen is just smaller, so you see one app at a time instead of side by side.</p>', updated_at = now() WHERE slug = 'help-mobile';

-- ─── help-keyboard ───────────────────────────────────────────────────────────
--changeset system:v5-help-accuracy-0065-keyboard
UPDATE content_cards
SET
    body_html  = '<p>If you''re on a computer, these keyboard shortcuts can speed things up:</p><table><thead><tr><th>Shortcut</th><th>What it does</th></tr></thead><tbody><tr><td><code>1</code> / <code>2</code> / <code>3</code></td><td>Focus app pane 1, 2, or 3</td></tr><tr><td><code>n</code></td><td>Create a new item in the focused app</td></tr></tbody></table><p><em>These shortcuts only work when you''re in the locker and not typing in a text field.</em></p>',
    updated_at = now()
WHERE slug = 'help-keyboard';
--rollback UPDATE content_cards SET body_html = '<p>If you''re on a computer, these shortcuts can speed things up:</p><table><thead><tr><th>Shortcut</th><th>What it does</th></tr></thead><tbody><tr><td><code>E</code></td><td>Enter/exit Edit Mode</td></tr><tr><td><code>1</code> / <code>2</code> / <code>3</code></td><td>Switch to app pane 1, 2, or 3</td></tr><tr><td><code>H</code></td><td>Go back to home screen</td></tr><tr><td><code>N</code></td><td>Create new item in current app</td></tr><tr><td><code>Esc</code></td><td>Close current view / go back</td></tr></tbody></table><p><em>These shortcuts only work when you''re in the locker and not typing in a text field.</em></p>', updated_at = now() WHERE slug = 'help-keyboard';

-- ─── help-stickers — hide until the feature is wired back into the UI ────────
-- The stickers UI lives in app-launcher.component which is no longer reachable.
-- Setting status=DRAFT keeps the article + tags intact but excludes it from the public help page.
--changeset system:v5-help-accuracy-0065-hide-stickers
UPDATE content_cards
SET
    status     = 'DRAFT',
    updated_at = now()
WHERE slug = 'help-stickers';
--rollback UPDATE content_cards SET status = 'PUBLISHED', updated_at = now() WHERE slug = 'help-stickers';
